default_language_version:
  python: python3.10

repos:   
  # native hints instead of `from typing` | List -> list
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'v1.0' # Version to check
    hooks:
      - id: upgrade-type-hints

  # Only for removing unused imports > Other staff done by Black
  - repo: https://github.com/myint/autoflake
    rev: "v1.4" # Version to check
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        
  - repo: local
    hooks:
    - id: update-requirements-txt
      name: update-requirements-txt
      description: 'Generate requirements.txt based on poetry.lock'
      entry: poetry
      args: [export, --format, requirements.txt, --output, requirements.txt]
      language: system
      pass_filenames: false