version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  mongoexperss:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment: 
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongodb:27017"
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "admin" 
      ME_CONFIG_BASICAUTH_PASSWORD: "pass"
    depends_on:
      mongodb:
        condition: service_healthy
    
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_SHA      
    ports:
      - "8000:8000"
    environment:
      BASE_URL: "http://promptsail.local"
      STATIC_DIRECTORY: "/static"
      MONGO_URL: "mongodb://root:password@mongodb:27017"
    depends_on:
      mongodb:
        condition: service_healthy
  spa:
    container_name: spa
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
        mongodb:
            condition: service_started
        app:
            condition: service_started
networks:
  internal-network:
    internal: true
  external-network:
