import { ThemeConfig } from 'antd';

const theme: ThemeConfig = {
    token: {
        wireframe: false,
        colorTextTertiary: '#0b1d1ca6',
        colorTextQuaternary: '#0b1d1c8c',
        colorPrimaryBg: '#eff9f8',
        colorPrimaryBgHover: '#dceceb',
        colorPrimaryBorder: '#b6d3d2',
        colorPrimaryBorderHover: '#a3c7c5',
        colorPrimaryHover: '#266360',
        colorPrimary: '#307c78',
        colorInfo: '#307c78',
        colorPrimaryActive: '#1d4a48',
        colorPrimaryTextHover: '#266360',
        colorPrimaryText: '#307c78',
        colorPrimaryTextActive: '#1d4a48',
        colorSuccessBg: '#fcfffc',
        colorSuccessBgHover: '#e6f3e5',
        colorSuccessBorder: '#badbb8',
        colorSuccessBorderHover: '#a4cfa1',
        colorSuccessHover: '#1a6d13',
        colorSuccessActive: '#14520e',
        colorSuccessTextHover: '#1a6d13',
        colorSuccessTextActive: '#14520e',
        colorSuccessText: '#218818',
        colorSuccess: '#218818',
        colorWarningBg: '#fefdf8',
        colorWarningBgHover: '#fcf5e2',
        colorWarningBorder: '#f9e6b5',
        colorWarningBorderHover: '#f7df9f',
        colorWarningHover: '#c29215',
        colorWarning: '#edb21a',
        colorWarningActive: '#977110',
        colorWarningTextHover: '#c29215',
        colorWarningText: '#edb21a',
        colorWarningTextActive: '#977110',
        colorErrorBg: '#fdf9f9',
        colorErrorBgHover: '#f8e7e5',
        colorErrorBorder: '#edc3be',
        colorErrorBorderHover: '#e7b1ab',
        colorErrorHover: '#a0382a',
        colorError: '#c74635',
        colorErrorActive: '#782a20',
        colorErrorTextHover: '#a0382a',
        colorErrorText: '#c74635',
        colorErrorTextActive: '#782a20',
        colorLinkHover: '#276663',
        colorLinkActive: '#1d4a48',
        colorTextBase: '#0b1d1c',
        colorTextSecondary: '#0b1d1cbf',
        colorBgMask: '#0b1d1c73'
    },
    components: {
        Button: {
            paddingInline: 16,
            paddingInlineLG: 16
        },
        Layout: {
            headerBg: '#FFFFFF',
            headerPadding: '0 24px',
            siderBg: '#0B1D1C'
        },
        Menu: {
            colorText: '#FFF',
            iconSize: 16,
            itemBg: '#0B1D1C',
            itemActiveBg: '#FFFFFF26',
            itemHoverBg: '#FFFFFF0A',
            itemMarginBlock: 6,
            itemMarginInline: 16,
            itemSelectedColor: '#FFF',
            itemSelectedBg: '#1D4A48'
        },
        Typography: {
            colorError: '#C74635',
            colorErrorHover: '#C74635',
            colorErrorActive: '#C74635',
            colorLink: '#307C78',
            colorLinkActive: '#307C78',
            colorLinkHover: '#307C78',
            colorSuccess: '#218818',
            colorText: '#0B1D1CE0',
            colorTextDescription: '#0B1D1CA6',
            colorTextDisabled: '#0B1D1C8C',
            colorTextHeading: '#0B1D1CE0',
            colorWarning: '#EDB21A',
            fontFamily: 'Roboto Flex',
            fontSize: 14,
            fontSizeHeading1: 38,
            fontSizeHeading2: 30,
            fontSizeHeading3: 24,
            fontSizeHeading4: 20,
            fontSizeHeading5: 16,
            lineHeight: 1.5,
            lineHeightHeading1: 2.875,
            lineHeightHeading2: 2.375,
            lineHeightHeading3: 2,
            lineHeightHeading4: 1.75,
            lineHeightHeading5: 1.5,
            linkDecoration: 'underline',
            titleMarginBottom: '0',
            titleMarginTop: '0'
        }
    }
};

export default theme;
