import { ThemeConfig } from 'antd';

const theme: ThemeConfig = {
    token: {
        wireframe: false,
        colorPrimaryBg: '#0e2524',
        colorPrimaryBgHover: '#133230',
        colorPrimaryBorder: '#1d4a48',
        colorPrimaryBorderHover: '#266360',
        colorPrimaryHover: '#a3c7c5',
        colorPrimaryActive: '#b6d3d2',
        colorPrimaryTextHover: '#a3c7c5',
        colorPrimaryText: '#569592',
        colorPrimary: '#569592',
        colorInfo: '#569592',
        colorPrimaryTextActive: '#b6d3d2',
        colorSuccessBg: '#0a2907',
        colorSuccessBgHover: '#0d360a',
        colorSuccessBorder: '#14520e',
        colorSuccessBorderHover: '#1a6d13',
        colorSuccessHover: '#a4cfa1',
        colorSuccess: '#4da046',
        colorSuccessActive: '#badbb8',
        colorSuccessTextHover: '#a4cfa1',
        colorSuccessText: '#4da046',
        colorSuccessTextActive: '#badbb8',
        colorWarningBg: '#201803',
        colorWarningBgHover: '#302405',
        colorWarningBorder: '#574109',
        colorWarningBorderHover: '#6c510c',
        colorWarningHover: '#f7df9f',
        colorWarning: '#f0c146',
        colorWarningActive: '#f9e6b5',
        colorWarningTextHover: '#f7df9f',
        colorWarningText: '#f0c146',
        colorWarningTextActive: '#f9e6b5',
        colorErrorBg: '#230c09',
        colorErrorBgHover: '#3d1610',
        colorErrorBorder: '#782a20',
        colorErrorBorderHover: '#a0382a',
        colorErrorHover: '#e7b1ab',
        colorError: '#d26a5c',
        colorErrorActive: '#edc3be',
        colorErrorTextHover: '#e7b1ab',
        colorErrorText: '#d26a5c',
        colorErrorTextActive: '#edc3be',
        colorLink: '#569592',
        colorLinkHover: '#a3c7c5',
        colorLinkActive: '#b6d3d2',
        colorBgBase: '#040c0b',
        colorTextSecondary: '#ffffffbf',
        colorTextTertiary: '#ffffffa6',
        colorTextQuaternary: '#ffffff8c',
        colorBorder: '#1d4a48',
        colorBorderSecondary: '#133230',
        colorBgContainer: '#0b1d1c',
        colorBgElevated: '#133230',
        colorBgLayout: '#1d4a48',
        colorBgSpotlight: '#266360',
        colorBgMask: '#040c0b73'
    }
};

export default theme;
